name: praktikum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Bold.ttf
        - asset: fonts/Oswald/Oswald-ExtraLight.ttf
        - asset: fonts/Oswald/Oswald-Light.ttf
        - asset: fonts/Oswald/Oswald-Medium.ttf
        - asset: fonts/Oswald/Oswald-Regular.ttf
        - asset: fonts/Oswald/Oswald-SemiBold.ttf